"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { SlidersHorizontal, Search, X, ArrowRight } from "lucide-react";
import { useStore } from "./store-provider";
import { ProductCard } from "./product-card";
import { Modal } from "./modal";
import { categories } from "@/lib/demo-products";
import { productPrice } from "@/lib/types";
export function Catalog() {
  const params = useSearchParams(); const { products } = useStore();
  const [category, setCategory] = useState(params.get("categoria") ?? "");
  const [brand, setBrand] = useState(""); const [maxPrice, setMaxPrice] = useState("");
  const [available, setAvailable] = useState(false); const [sale, setSale] = useState(params.get("ofertas") === "true");
  const [query, setQuery] = useState(params.get("busca") ?? ""); const [sort, setSort] = useState("new"); const [drawer, setDrawer] = useState(false);
  const brands = [...new Set(products.map(p => p.brand.name))].sort();
  const normalize = (str: string) => str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const filtered = products.filter(p => (!category || p.category.slug === category) && (!brand || p.brand.name === brand) && (!maxPrice || productPrice(p) <= Number(maxPrice) * 100) && (!available || p.stock > 0) && (!sale || p.promotionalPriceCents !== null) && normalize(`${p.name} ${p.brand.name} ${p.category.name}`).includes(normalize(query))).sort((a, b) => sort === "low" ? productPrice(a) - productPrice(b) : sort === "high" ? productPrice(b) - productPrice(a) : sort === "az" ? a.name.localeCompare(b.name, "pt-BR") : b.createdAt.localeCompare(a.createdAt));
  const clear = () => { setCategory(""); setBrand(""); setMaxPrice(""); setAvailable(false); setSale(false); setQuery(""); };
  const activeCount = [category, brand, maxPrice, available, sale].filter(Boolean).length;
  function filters() { return <div className="filters"><fieldset><legend>Categorias</legend><label className="filter-option"><input type="radio" name={drawer ? "mobile-category" : "category"} checked={!category} onChange={() => setCategory("")} />Todos os produtos</label>{categories.map(c => <label className="filter-option" key={c.slug}><input type="radio" name={drawer ? "mobile-category" : "category"} checked={category === c.slug} onChange={() => setCategory(c.slug)} />{c.name}</label>)}</fieldset><label className="filter-label">Marca<select value={brand} onChange={e => setBrand(e.target.value)}><option value="">Todas as marcas</option>{brands.map(b => <option key={b}>{b}</option>)}</select></label><label className="filter-label">Faixa de preço<select value={maxPrice} onChange={e => setMaxPrice(e.target.value)}><option value="">Todos os preços</option><option value="15">Até R$ 15</option><option value="30">Até R$ 30</option><option value="50">Até R$ 50</option><option value="100">Até R$ 100</option></select></label><fieldset><legend>Disponibilidade</legend><label className="filter-option"><input type="checkbox" checked={available} onChange={e => setAvailable(e.target.checked)} />Somente em estoque</label><label className="filter-option"><input type="checkbox" checked={sale} onChange={e => setSale(e.target.checked)} />Somente ofertas</label></fieldset>{activeCount > 0 && <button className="text-link" onClick={clear}>Limpar filtros <X size={15} /></button>}</div>; }
  return <div className="container page-space"><nav className="breadcrumbs"><Link href="/">Início</Link><span>/</span><span>Catálogo</span></nav><div className="catalog-title"><span className="eyebrow">SEUS PRÓXIMOS ESSENCIAIS</span><h1>{categories.find(c => c.slug === category)?.name ?? (sale ? "Pequenos preços, grandes achados" : "Encontre seu básico")}</h1><p>Escolha com calma. Coloque na sacola. Deixe o resto com a gente.</p></div><div className="catalog-layout"><aside className="catalog-sidebar"><div className="filter-heading"><SlidersHorizontal size={18} /><h2>Filtrar produtos</h2></div>{filters()}</aside><div className="catalog-results"><div className="catalog-controls"><div className="catalog-search"><Search size={18} /><input aria-label="Buscar no catálogo" placeholder="Produto, marca ou categoria" value={query} onChange={e => setQuery(e.target.value)} />{query && <button aria-label="Limpar busca" onClick={() => setQuery("")}><X size={16} /></button>}</div><button className="filter-mobile button secondary" onClick={() => setDrawer(true)}><SlidersHorizontal size={17} />Filtrar{activeCount > 0 && ` (${activeCount})`}</button><label className="sort-label"><span>Ordenar por</span><select aria-label="Ordenar produtos" value={sort} onChange={e => setSort(e.target.value)}><option value="new">Novidades</option><option value="low">Menor preço</option><option value="high">Maior preço</option><option value="az">Nome A–Z</option></select></label></div><div className="results-count">{filtered.length} {filtered.length === 1 ? "produto" : "produtos"}{query && ` para “${query}”`}</div>{filtered.length ? <div className="product-grid catalog-product-grid">{filtered.map(p => <ProductCard product={p} key={p.id} />)}</div> : <div className="empty-state"><Search size={38} strokeWidth={1.3} /><h2>Nenhum básico por aqui ainda</h2><p>Tente outro nome ou ajuste os filtros para encontrar seus favoritos.</p><button onClick={clear} className="button primary">Ver todos os produtos <ArrowRight size={17} /></button></div>}<p className="demo-note">Produtos fictícios para testes. Ilustrações e fotografias de ambientação não representam o catálogo real.</p></div></div><Modal open={drawer} onClose={() => setDrawer(false)} title="Filtrar produtos" drawer>{filters()}<button className="button primary full" onClick={() => setDrawer(false)}>Ver {filtered.length} produtos</button></Modal></div>;
}
