"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ShoppingBag, ArrowRight, Truck, MessageCircle, Check, ChevronRight } from "lucide-react";
import { useStore } from "./store-provider";
import { ProductCard, ProductImage } from "./product-card";
import { Quantity } from "./quantity";
import { money, storeConfig } from "@/lib/store-config";
import { productPrice, type StoreProduct } from "@/lib/types";
export function ProductDetail({ product }: { product: StoreProduct }) {
  const { add, products } = useStore(); const router = useRouter();
  const [quantity, setQuantity] = useState(1); const [imageIndex, setImageIndex] = useState(0);
  const related = products.filter(p => p.category.slug === product.category.slug && p.id !== product.id).slice(0, 4);
  return <div className="container page-space"><nav className="breadcrumbs"><Link href="/">Início</Link><ChevronRight size={12} /><Link href="/produtos">Catálogo</Link><ChevronRight size={12} /><Link href={`/produtos?categoria=${product.category.slug}`}>{product.category.name}</Link></nav><div className="product-detail"><div><div className="detail-visual">{product.images.length > 0 ? <Image src={product.images[imageIndex].url} alt={product.images[imageIndex].alt} fill priority sizes="(max-width: 767px) 100vw, 50vw" className="product-image" /> : <ProductImage product={product} />}</div>{product.images.length > 1 && <div className="gallery">{product.images.map((image, i) => <button key={image.url} className={imageIndex === i ? "selected" : ""} onClick={() => setImageIndex(i)} aria-label={`Ver imagem ${i + 1}`} aria-pressed={imageIndex === i}><Image src={image.url} alt={image.alt} width={72} height={72} /></button>)}</div>}<p className="demo-note">Imagem ilustrativa · produto fictício para testes</p></div><div className="detail-info"><span className="eyebrow">{product.brand.name}</span><h1>{product.name}</h1><p className="detail-category">{product.category.name}</p><div className="detail-price">{product.promotionalPriceCents !== null && <span className="old-price">{money(product.priceCents)}</span>}<strong>{money(productPrice(product))}</strong>{product.promotionalPriceCents !== null && <span className="sale-label">Um achado especial</span>}</div><p className={`availability ${product.stock === 0 ? "sold-out" : ""}`}><Check size={16} />{product.stock > 0 ? "Disponível para adicionar à sacola" : "Produto indisponível no momento"}</p><div className="detail-description"><h2>Sobre esse básico</h2><p>{product.description}</p></div><div className="detail-buy"><label>Quantidade</label><Quantity value={quantity} max={product.stock} onChange={setQuantity} label={product.name} /><button className="button primary full" disabled={product.stock === 0} onClick={() => add(product, quantity)}><ShoppingBag size={19} />{product.stock ? "Adicionar ao carrinho" : "Indisponível"}</button><button className="button secondary full" disabled={product.stock === 0} onClick={() => { if (add(product, quantity)) router.push("/carrinho"); }}>Comprar agora <ArrowRight size={17} /></button></div><div className="detail-reassurance"><p><Truck size={18} />Entrega de teste: {money(storeConfig.deliveryFeeCents)}</p><p><MessageCircle size={18} />Pedido confirmado com atendimento pelo WhatsApp</p></div></div></div>{related.length > 0 && <section className="related"><div className="section-heading"><h2>Mais detalhes para sua rotina</h2><Link className="text-link" href={`/produtos?categoria=${product.category.slug}`}>Ver categoria <ArrowRight size={17} /></Link></div><div className="product-grid">{related.map(p => <ProductCard key={p.id} product={p} />)}</div></section>}</div>;
}
